In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
dataset= pd.read_csv("Preprocessed_dataset.csv")
dataset

Age  Gender  Income CampaignChannel   CampaignType      AdSpend  \
0      56  Female  136912    Social Media      Awareness  6497.870068   
1      69    Male   41760           Email      Retention  3898.668606   
2      46  Female   88456             PPC      Awareness  1546.429596   
3      32  Female   44085             PPC     Conversion   539.525936   
4      60  Female   83964             PPC     Conversion  1678.043573   
...   ...     ...     ...             ...            ...          ...   
7995   21    Male   24849           Email      Awareness  8518.308575   
7996   43  Female   44718             SEO      Retention  1424.613446   
7997   28  Female  125471        Referral  Consideration  4609.534635   
7998   19  Female  107862             PPC  Consideration  9476.106354   
7999   31  Female   93002           Email      Awareness  7743.627070   

      ClickThroughRate  ConversionRate  WebsiteVisits  PagesPerVisit  \
0             0.043919        0.088031              0       2.399017   
1             0.155725        0.182725             42       2.917138   
2             0.277490        0.076423              2       8.223619   
3             0.137611        0.088004             47       4.540939   
4             0.252851        0.109940              0       2.046847   
...                ...             ...            ...            ...   
7995          0.243792        0.116773             23       9.693602   
7996          0.236740        0.190061             49       9.499010   
7997          0.056526        0.133826             35       2.853241   
7998          0.023961        0.138386             49       1.002964   
7999          0.185670        0.057228             15       6.964739   

      TimeOnSite  SocialShares  EmailOpens  EmailClicks  PreviousPurchases  \
0       7.396803            19           6            9                  4   
1       5.352549             5           2            7                  2   
2      13.794901             0          11            2                  8   
3      14.688363            89           2            2                  0   
4      13.993370             6           6            6                  8   
...          ...           ...         ...          ...                ...   
7995   14.227794            70          13            6                  7   
7996    3.501106            52          13            1                  5   
7997   14.618323            38          16            0                  3   
7998    3.876623            86           1            5                  7   
7999   12.763660             2          18            9                  9   

      LoyaltyPoints  Conversion  
0               688           1  
1              3459           1  
2              2337           1  
3              2463           1  
4              4345           1  
...             ...         ...  
7995            286           0  
7996           1502           0  
7997            738           1  
7998           2709           1  
7999            341           0  

[8000 rows x 17 columns]

In [2]:
dataset1=pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset1

Age  Income      AdSpend  ClickThroughRate  ConversionRate  \
0      56  136912  6497.870068          0.043919        0.088031   
1      69   41760  3898.668606          0.155725        0.182725   
2      46   88456  1546.429596          0.277490        0.076423   
3      32   44085   539.525936          0.137611        0.088004   
4      60   83964  1678.043573          0.252851        0.109940   
...   ...     ...          ...               ...             ...   
7995   21   24849  8518.308575          0.243792        0.116773   
7996   43   44718  1424.613446          0.236740        0.190061   
7997   28  125471  4609.534635          0.056526        0.133826   
7998   19  107862  9476.106354          0.023961        0.138386   
7999   31   93002  7743.627070          0.185670        0.057228   

      WebsiteVisits  PagesPerVisit  TimeOnSite  SocialShares  EmailOpens  ...  \
0                 0       2.399017    7.396803            19           6  ...   
1                42       2.917138    5.352549             5           2  ...   
2                 2       8.223619   13.794901             0          11  ...   
3                47       4.540939   14.688363            89           2  ...   
4                 0       2.046847   13.993370             6           6  ...   
...             ...            ...         ...           ...         ...  ...   
7995             23       9.693602   14.227794            70          13  ...   
7996             49       9.499010    3.501106            52          13  ...   
7997             35       2.853241   14.618323            38          16  ...   
7998             49       1.002964    3.876623            86           1  ...   
7999             15       6.964739   12.763660             2          18  ...   

      LoyaltyPoints  Conversion  Gender_Male  CampaignChannel_PPC  \
0               688           1            0                    0   
1              3459           1            1                    0   
2              2337           1            0                    1   
3              2463           1            0                    1   
4              4345           1            0                    1   
...             ...         ...          ...                  ...   
7995            286           0            1                    0   
7996           1502           0            0                    0   
7997            738           1            0                    0   
7998           2709           1            0                    1   
7999            341           0            0                    0   

      CampaignChannel_Referral  CampaignChannel_SEO  \
0                            0                    0   
1                            0                    0   
2                            0                    0   
3                            0                    0   
4                            0                    0   
...                        ...                  ...   
7995                         0                    0   
7996                         0                    1   
7997                         1                    0   
7998                         0                    0   
7999                         0                    0   

      CampaignChannel_Social Media  CampaignType_Consideration  \
0                                1                           0   
1                                0                           0   
2                                0                           0   
3                                0                           0   
4                                0                           0   
...                            ...                         ...   
7995                             0                           0   
7996                             0                           0   
7997                             0                           1   
7998                             0                           1   


In [3]:
indep_x= dataset1.drop('Conversion',axis=1)
dep_y=dataset1['Conversion']

In [4]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size = 0.33, random_state = 42)  

In [5]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

In [6]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
def selectkbest(X_train_resampled,y_train_resampled,n):
        test = SelectKBest(score_func=chi2, k=n)
        X_train_selected = test.fit_transform(X_train_resampled,y_train_resampled )
        featurename= test.get_support(indices=True)
        selected_features=dataset1.columns[featurename]
        features=selected_features.to_list()
        print(f"The {n} features are",features)
        X_test_selected= test.transform(X_test)
        return X_train_selected,X_test_selected

In [7]:
X_train_selected,X_test_selected=selectkbest(X_train_resampled,y_train_resampled,12)
X_train_selected

The 12 features are ['Income', 'AdSpend', 'WebsiteVisits', 'PagesPerVisit', 'TimeOnSite', 'SocialShares', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints', 'CampaignChannel_Social Media', 'CampaignType_Consideration']


array([[4.83950000e+04, 1.56750425e+03, 7.00000000e+00, ...,
        9.18000000e+02, 0.00000000e+00, 1.00000000e+00],
       [1.24565000e+05, 7.83216146e+03, 3.00000000e+00, ...,
        2.00800000e+03, 1.00000000e+00, 0.00000000e+00],
       [2.78990000e+04, 9.43834517e+03, 4.90000000e+01, ...,
        4.41600000e+03, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.18474000e+05, 2.81740322e+03, 1.00000000e+01, ...,
        3.65000000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.28877000e+05, 1.18394811e+03, 4.00000000e+00, ...,
        2.88100000e+03, 1.00000000e+00, 0.00000000e+00],
       [6.08880000e+04, 3.81224098e+03, 4.00000000e+01, ...,
        2.15100000e+03, 0.00000000e+00, 0.00000000e+00]])

In [8]:
from sklearn.model_selection import GridSearchCV

def cm_prediction(grid_search,X_test_selected):
     y_pred = grid_search.predict(X_test_selected)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  grid_search,Accuracy,report,X_test_selected,y_test,cm

def logistic(X_train_resampled,y_train_resampled,X_test_selected):       
        from sklearn.linear_model import LogisticRegression
        param_grid = {'C': [0.01, 0.1, 1, 10,100], 'penalty': ['l1', 'l2'], 'solver': ['liblinear', 'saga','lbfgs'],'max_iter': [50,100],'random_state':[42]}
        grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5, scoring='accuracy', n_jobs=-1,refit=True)
        grid_search.fit(X_train_selected, y_train_resampled )
        grid_search,Accuracy,report,X_test_selected,y_test,cm=cm_prediction(grid_search,X_test_selected)
        return  grid_search,Accuracy,report,X_test_selected,y_test,cm 

def svm_NL(X_train_resampled,y_train_resampled,X_test):
        from sklearn.svm import SVC
        param_grid={'kernel':['rbf','poly'], 'C':[0.1, 1, 10], 'gamma':['scale', 'auto', 0.1, 1], 'random_state':[42], 'degree':[2]}
        grid_search= GridSearchCV(SVC(probability=True), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'accuracy')
        grid_search.fit(X_train_resampled, y_train_resampled)
        grid_search,Accuracy,report,X_test,y_test,cm=cm_prediction(grid_search,X_test)
        return  grid_search,Accuracy,report,X_test,y_test,cm

def Decision(X_train_resampled,y_train_resampled,X_test_selected):
        from sklearn.tree import DecisionTreeClassifier
        param_grid={'criterion':["gini", "entropy", "log_loss"], 'splitter': ["best", "random"],'max_features': [None,"sqrt", "log2"], 'random_state':[42]}
        grid_search= GridSearchCV(DecisionTreeClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'accuracy' )
        grid_search.fit(X_train_selected,y_train_resampled)
        grid_search,Accuracy,report,X_test_selected,y_test,cm=cm_prediction(grid_search,X_test_selected)
        return  grid_search,Accuracy,report,X_test_selected,y_test,cm

def random(X_train_resampled,y_train_resampled,X_test_selected):
        
        from sklearn.ensemble import RandomForestClassifier
        param_grid={'criterion':["gini", "entropy", "log_loss"],'max_features': [None,"sqrt", "log2"], 'n_estimators':[10,50,100],'random_state':[42]}
        grid_search= GridSearchCV(RandomForestClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'accuracy' )
        grid_search.fit(X_train_selected, y_train_resampled)
        grid_search,Accuracy,report,X_test_selected,y_test,cm=cm_prediction(grid_search,X_test_selected)
        return  grid_search,Accuracy,report,X_test_selected,y_test,cm

def Xgboost(X_train_resampled,y_train_resampled,X_test_selected):
        from xgboost import XGBClassifier
        from collections import Counter
        counter = Counter(y_train)  # Count class occurrences
        ratio = counter[0] / counter[1]
        param_grid = {'n_estimators': [100, 300],'max_depth': [3, 6],'learning_rate': [0.01, 0.1, 0.3],'subsample': [ 0.8, 1.0],'colsample_bytree': [0.7, 1.0],'gamma': [1, 5]}
        grid_search = GridSearchCV(XGBClassifier(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring= 'accuracy' )
        grid_search.fit(X_train_selected, y_train_resampled)
        grid_search,Accuracy,report,X_test_selected,y_test,cm=cm_prediction(grid_search,X_test_selected)
        return  grid_search,Accuracy,report,X_test_selected,y_test,cm

In [9]:
grid_search, Accuracy, report, X_test, y_test, cm = logistic(X_train_selected,y_train_resampled, X_test_selected)
print("Logistic Regression Classification Report:\n")
print(cm)
print(report) 

Logistic Regression Classification Report:

[[ 227   94]
 [ 686 1633]]
              precision    recall  f1-score   support

           0       0.25      0.71      0.37       321
           1       0.95      0.70      0.81      2319

    accuracy                           0.70      2640
   macro avg       0.60      0.71      0.59      2640
weighted avg       0.86      0.70      0.75      2640



In [10]:
#grid_search, Accuracy, report, X_test, y_test, cm = svm_NL(X_train_resampled, y_train_resampled, X_test)
#print("\nSVM Non-Linear Classification Report:")
#print(cm)
#print(report) 

In [11]:
grid_search, Accuracy, report, X_test_selected, y_test, cm = Decision(X_train_selected,y_train_resampled, X_test_selected)
print("\nDecision Tree Classification Report:")
print(cm)
print(report)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

Decision Tree Classification Report:
[[ 117  204]
 [ 236 2083]]
              precision    recall  f1-score   support

           0       0.33      0.36      0.35       321
           1       0.91      0.90      0.90      2319

    accuracy                           0.83      2640
   macro avg       0.62      0.63      0.63      2640
weighted avg       0.84      0.83      0.84      2640



In [12]:
grid_search, Accuracy, report, X_test_selected, y_test, cm = random(X_train_selected,y_train_resampled, X_test_selected)
print("\nRandom Forest Classification Report:")
print(cm)
print(report) 

Fitting 5 folds for each of 27 candidates, totalling 135 fits

Random Forest Classification Report:
[[  99  222]
 [  47 2272]]
              precision    recall  f1-score   support

           0       0.68      0.31      0.42       321
           1       0.91      0.98      0.94      2319

    accuracy                           0.90      2640
   macro avg       0.79      0.64      0.68      2640
weighted avg       0.88      0.90      0.88      2640



In [13]:
grid_search, Accuracy, report, X_test_selected, y_test, cm = Xgboost(X_train_selected,y_train_resampled, X_test_selected)
print("\n XgboostClassification Report:")
print(report)
print(cm)

Fitting 5 folds for each of 96 candidates, totalling 480 fits

 XgboostClassification Report:
              precision    recall  f1-score   support

           0       0.55      0.49      0.52       321
           1       0.93      0.94      0.94      2319

    accuracy                           0.89      2640
   macro avg       0.74      0.72      0.73      2640
weighted avg       0.88      0.89      0.89      2640

[[ 157  164]
 [ 130 2189]]


In [19]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resampled1, y_train_resampled1 = smote.fit_resample(X_train, y_train)