In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
dataset= pd.read_csv("Preprocessed_dataset.csv")
dataset1=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [2]:
indep_x= dataset1.drop('Conversion',axis=1)
dep_y=dataset1['Conversion']

In [3]:
indep_x

Age  Income      AdSpend  ClickThroughRate  ConversionRate  \
0      56  136912  6497.870068          0.043919        0.088031   
1      69   41760  3898.668606          0.155725        0.182725   
2      46   88456  1546.429596          0.277490        0.076423   
3      32   44085   539.525936          0.137611        0.088004   
4      60   83964  1678.043573          0.252851        0.109940   
...   ...     ...          ...               ...             ...   
7995   21   24849  8518.308575          0.243792        0.116773   
7996   43   44718  1424.613446          0.236740        0.190061   
7997   28  125471  4609.534635          0.056526        0.133826   
7998   19  107862  9476.106354          0.023961        0.138386   
7999   31   93002  7743.627070          0.185670        0.057228   

      WebsiteVisits  PagesPerVisit  TimeOnSite  SocialShares  EmailOpens  ...  \
0                 0       2.399017    7.396803            19           6  ...   
1                42       2.917138    5.352549             5           2  ...   
2                 2       8.223619   13.794901             0          11  ...   
3                47       4.540939   14.688363            89           2  ...   
4                 0       2.046847   13.993370             6           6  ...   
...             ...            ...         ...           ...         ...  ...   
7995             23       9.693602   14.227794            70          13  ...   
7996             49       9.499010    3.501106            52          13  ...   
7997             35       2.853241   14.618323            38          16  ...   
7998             49       1.002964    3.876623            86           1  ...   
7999             15       6.964739   12.763660             2          18  ...   

      PreviousPurchases  LoyaltyPoints  Gender_Male  CampaignChannel_PPC  \
0                     4            688            0                    0   
1                     2           3459            1                    0   
2                     8           2337            0                    1   
3                     0           2463            0                    1   
4                     8           4345            0                    1   
...                 ...            ...          ...                  ...   
7995                  7            286            1                    0   
7996                  5           1502            0                    0   
7997                  3            738            0                    0   
7998                  7           2709            0                    1   
7999                  9            341            0                    0   

      CampaignChannel_Referral  CampaignChannel_SEO  \
0                            0                    0   
1                            0                    0   
2                            0                    0   
3                            0                    0   
4                            0                    0   
...                        ...                  ...   
7995                         0                    0   
7996                         0                    1   
7997                         1                    0   
7998                         0                    0   
7999                         0                    0   

      CampaignChannel_Social Media  CampaignType_Consideration  \
0                                1                           0   
1                                0                           0   
2                                0                           0   
3                                0                           0   
4                                0                           0   
...                            ...                         ...   
7995                             0                           0   
7996                             0                           0   
7997                             0              

In [4]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
def selectkbest(indep_x,dep_y,n):
        test = SelectKBest(score_func=mutual_info_classif, k=n)
        fit1= test.fit(indep_x,dep_y)
        featurename= fit1.get_support(indices=True)
        selected_features=dataset1.columns[featurename]
        features=selected_features.to_list()
        print(f"The {n} features are",features)
        selectk_features = fit1.transform(indep_x)
        return selectk_features

In [5]:
selectk_features=selectkbest(indep_x,dep_y,12)
selectk_features

The 12 features are ['AdSpend', 'ClickThroughRate', 'ConversionRate', 'WebsiteVisits', 'PagesPerVisit', 'TimeOnSite', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints', 'CampaignChannel_Referral', 'CampaignType_Consideration']


array([[6.49787007e+03, 4.39185107e-02, 8.80314121e-02, ...,
        6.88000000e+02, 0.00000000e+00, 0.00000000e+00],
       [3.89866861e+03, 1.55725071e-01, 1.82724683e-01, ...,
        3.45900000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.54642960e+03, 2.77490369e-01, 7.64227201e-02, ...,
        2.33700000e+03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [4.60953464e+03, 5.65259173e-02, 1.33826123e-01, ...,
        7.38000000e+02, 0.00000000e+00, 0.00000000e+00],
       [9.47610635e+03, 2.39612921e-02, 1.38386181e-01, ...,
        2.70900000e+03, 0.00000000e+00, 0.00000000e+00],
       [7.74362707e+03, 1.85670096e-01, 5.72280791e-02, ...,
        3.41000000e+02, 0.00000000e+00, 0.00000000e+00]])

In [6]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
def split_scalar(indep_x,dep_y):
        X_train, X_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size = 0.2, random_state = 42)   
        return X_train, X_test, y_train, y_test

In [7]:
X_train, X_test, y_train, y_test=split_scalar(selectk_features,dep_y)
X_train

array([[5.68917510e+03, 2.79866718e-01, 1.59560370e-01, ...,
        3.99000000e+03, 0.00000000e+00, 1.00000000e+00],
       [5.42412261e+03, 2.08562109e-01, 1.01926484e-01, ...,
        3.76100000e+03, 0.00000000e+00, 1.00000000e+00],
       [3.92795630e+03, 1.71734694e-01, 8.57368651e-02, ...,
        3.61200000e+03, 1.00000000e+00, 1.00000000e+00],
       ...,
       [4.35558657e+03, 1.84523200e-01, 3.40195045e-02, ...,
        3.98000000e+02, 0.00000000e+00, 0.00000000e+00],
       [6.74011615e+03, 2.56331900e-01, 1.33938647e-01, ...,
        3.37500000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.94690170e+03, 2.93389681e-01, 1.71929785e-01, ...,
        2.75900000e+03, 1.00000000e+00, 0.00000000e+00]])

In [8]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [9]:
from sklearn.model_selection import GridSearchCV

In [11]:
from sklearn.linear_model import LogisticRegression
LRC=LogisticRegression(random_state = 0,)
LRC.fit(X_resampled, y_resampled)
LRC_probs =LRC.predict_proba(X_test)[:, 1]
LRC_probs

array([0.61603639, 0.40822484, 0.50861767, ..., 0.56152493, 0.42474768,
       0.64952312])

In [12]:
from xgboost import XGBClassifier
#from collections import Counter
#counter = Counter(y_train)  # Count class occurrences
#ratio = counter[0] / counter[1]
# Meta-Model (different from base models)
param_grid_XGB={'n_estimators': [100],'max_depth': [3, 6],'learning_rate': [0.01, 0.1],'subsample': [ 0.8],'colsample_bytree': [0.7,1.0],'gamma': [1]}
grid_XGB =  GridSearchCV(XGBClassifier(), param_grid_XGB, cv=5)
grid_XGB.fit(X_resampled,y_resampled)
XGB_probs = grid_XGB.predict_proba(X_test)[:, 1]
XGB_probs

array([0.4537054 , 0.9604091 , 0.33225453, ..., 0.90424824, 0.9430394 ,
       0.98068684], dtype=float32)

In [17]:
import numpy as np
from sklearn.metrics import f1_score, precision_recall_curve

# Initialize variables
best_f1 = 0
best_w1 = 0
best_w2 = 0
best_threshold = 0.5  # Default threshold

# Loop over possible weights for LRC (w1) from 0.1 to 1.0
for w1 in np.arange(0.1, 1.1, 0.1):  # Include 1.0
    w2 = 1 - w1  # Complementary weight for XGB
    blended_probs = (w1 * LRC_probs) + (w2 * XGB_probs)  # Blend probabilities
    
    # Find the best threshold for the current weights
    precision, recall, thresholds = precision_recall_curve(y_test, blended_probs)
    for threshold in thresholds:
        blended_preds = (blended_probs >= threshold).astype(int)
        f1 = f1_score(y_test, blended_preds)
        if f1 > best_f1:
            best_f1 = f1
            best_w1 = w1
            best_w2 = w2
            best_threshold = threshold

print(f"Best weights: LRC = {best_w1}, XGB = {best_w2}, Best threshold: {best_threshold}, Best F1-score: {best_f1}")

Best weights: LRC = 0.1, XGB = 0.9, Best threshold: 0.4752114368583798, Best F1-score: 0.9505361466620547


In [19]:
 #Blend models using the best weights
final_probs = (best_w1 * LRC_probs) + (best_w2 * XGB_probs)

# Apply the best threshold to make final predictions
final_pred = (final_probs >= best_threshold).astype(int)

# Evaluate the final predictions
from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:")
print(classification_report(y_test, final_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, final_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.43      0.54       194
           1       0.93      0.98      0.95      1406

    accuracy                           0.91      1600
   macro avg       0.82      0.70      0.74      1600
weighted avg       0.90      0.91      0.90      1600

Confusion Matrix:
[[  83  111]
 [  32 1374]]


In [14]:
# Blend models (weighted averaging)
final_probs = (0.4 * LRC_probs) + (0.6 * XGB_probs)  # Adjust weights if needed
final_pred= (final_probs > 0.5).astype(int)
final_pred

array([1, 1, 0, ..., 1, 1, 1])

In [15]:
# MUTUAL INFO CLASSIFICATION
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
report=classification_report(y_test, final_pred)
cm = confusion_matrix(y_test, final_pred)
print(report)
print(cm)

              precision    recall  f1-score   support

           0       0.68      0.44      0.53       194
           1       0.93      0.97      0.95      1406

    accuracy                           0.91      1600
   macro avg       0.80      0.70      0.74      1600
weighted avg       0.90      0.91      0.90      1600

[[  85  109]
 [  40 1366]]


In [13]:
from sklearn.metrics import f1_score
best_f1 = 0
best_w1 = 0
best_w2 = 0

for w1 in np.arange(0.1, 1.0, 0.1):
    w2 = 1 - w1
    blended_probs = (w1 * LRC_probs) + (w2 * XGB_probs)
    blended_preds = (blended_probs > 0.5).astype(int)
    
    f1 = f1_score(y_test, blended_preds)
    if f1 > best_f1:
        best_f1 = f1
        best_w1 = w1
        best_w2 = w2

print(f"Best weights: LRC = {best_w1}, XGB = {best_w2}, Best F1-score = {best_f1}")

Best weights: LRC = 0.4, XGB = 0.6, Best F1-score = 0.9482818465810482
