In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
dataset= pd.read_csv("Preprocessed_dataset.csv")
dataset1=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [2]:
indep_x= dataset1.drop('Conversion',axis=1)
dep_y=dataset1['Conversion']

In [3]:
indep_x

Age  Income      AdSpend  ClickThroughRate  ConversionRate  \
0      56  136912  6497.870068          0.043919        0.088031   
1      69   41760  3898.668606          0.155725        0.182725   
2      46   88456  1546.429596          0.277490        0.076423   
3      32   44085   539.525936          0.137611        0.088004   
4      60   83964  1678.043573          0.252851        0.109940   
...   ...     ...          ...               ...             ...   
7995   21   24849  8518.308575          0.243792        0.116773   
7996   43   44718  1424.613446          0.236740        0.190061   
7997   28  125471  4609.534635          0.056526        0.133826   
7998   19  107862  9476.106354          0.023961        0.138386   
7999   31   93002  7743.627070          0.185670        0.057228   

      WebsiteVisits  PagesPerVisit  TimeOnSite  SocialShares  EmailOpens  ...  \
0                 0       2.399017    7.396803            19           6  ...   
1                42       2.917138    5.352549             5           2  ...   
2                 2       8.223619   13.794901             0          11  ...   
3                47       4.540939   14.688363            89           2  ...   
4                 0       2.046847   13.993370             6           6  ...   
...             ...            ...         ...           ...         ...  ...   
7995             23       9.693602   14.227794            70          13  ...   
7996             49       9.499010    3.501106            52          13  ...   
7997             35       2.853241   14.618323            38          16  ...   
7998             49       1.002964    3.876623            86           1  ...   
7999             15       6.964739   12.763660             2          18  ...   

      PreviousPurchases  LoyaltyPoints  Gender_Male  CampaignChannel_PPC  \
0                     4            688            0                    0   
1                     2           3459            1                    0   
2                     8           2337            0                    1   
3                     0           2463            0                    1   
4                     8           4345            0                    1   
...                 ...            ...          ...                  ...   
7995                  7            286            1                    0   
7996                  5           1502            0                    0   
7997                  3            738            0                    0   
7998                  7           2709            0                    1   
7999                  9            341            0                    0   

      CampaignChannel_Referral  CampaignChannel_SEO  \
0                            0                    0   
1                            0                    0   
2                            0                    0   
3                            0                    0   
4                            0                    0   
...                        ...                  ...   
7995                         0                    0   
7996                         0                    1   
7997                         1                    0   
7998                         0                    0   
7999                         0                    0   

      CampaignChannel_Social Media  CampaignType_Consideration  \
0                                1                           0   
1                                0                           0   
2                                0                           0   
3                                0                           0   
4                                0                           0   
...                            ...                         ...   
7995                             0                           0   
7996                             0                           0   
7997                             0              

In [4]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
def selectkbest(indep_x,dep_y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_x,dep_y)
        featurename= fit1.get_support(indices=True)
        selected_features=dataset1.columns[featurename]
        features=selected_features.to_list()
        print(f"The {n} features are",features)
        selectk_features = fit1.transform(indep_x)
        return selectk_features

In [19]:
selectk_features=selectkbest(indep_x,dep_y,12)
selectk_features

The 8 features are ['Income', 'AdSpend', 'WebsiteVisits', 'TimeOnSite', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints']


array([[1.36912000e+05, 6.49787007e+03, 0.00000000e+00, ...,
        9.00000000e+00, 4.00000000e+00, 6.88000000e+02],
       [4.17600000e+04, 3.89866861e+03, 4.20000000e+01, ...,
        7.00000000e+00, 2.00000000e+00, 3.45900000e+03],
       [8.84560000e+04, 1.54642960e+03, 2.00000000e+00, ...,
        2.00000000e+00, 8.00000000e+00, 2.33700000e+03],
       ...,
       [1.25471000e+05, 4.60953464e+03, 3.50000000e+01, ...,
        0.00000000e+00, 3.00000000e+00, 7.38000000e+02],
       [1.07862000e+05, 9.47610635e+03, 4.90000000e+01, ...,
        5.00000000e+00, 7.00000000e+00, 2.70900000e+03],
       [9.30020000e+04, 7.74362707e+03, 1.50000000e+01, ...,
        9.00000000e+00, 9.00000000e+00, 3.41000000e+02]])

In [20]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
def split_scalar(indep_x,dep_y):
        X_train, X_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size = 0.2, random_state = 42)   
        return X_train, X_test, y_train, y_test

In [21]:
X_train, X_test, y_train, y_test=split_scalar(selectk_features,dep_y)
X_train

array([[9.38850000e+04, 5.68917510e+03, 1.20000000e+01, ...,
        8.00000000e+00, 0.00000000e+00, 3.99000000e+03],
       [1.32985000e+05, 5.42412261e+03, 3.60000000e+01, ...,
        4.00000000e+00, 5.00000000e+00, 3.76100000e+03],
       [1.08713000e+05, 3.92795630e+03, 0.00000000e+00, ...,
        5.00000000e+00, 9.00000000e+00, 3.61200000e+03],
       ...,
       [1.11150000e+05, 4.35558657e+03, 1.50000000e+01, ...,
        6.00000000e+00, 5.00000000e+00, 3.98000000e+02],
       [5.54020000e+04, 6.74011615e+03, 1.00000000e+01, ...,
        3.00000000e+00, 8.00000000e+00, 3.37500000e+03],
       [1.28061000e+05, 1.94690170e+03, 1.00000000e+00, ...,
        0.00000000e+00, 4.00000000e+00, 2.75900000e+03]])

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
from sklearn.ensemble import StackingClassifier

In [26]:
base_models=[('LRC',LogisticRegression(random_state = 0,class_weight="balanced")),('DTC',DecisionTreeClassifier(criterion = 'entropy', random_state = 0,class_weight="balanced")),('RFC', RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0,class_weight="balanced"))]

In [27]:
from xgboost import XGBClassifier
from collections import Counter
counter = Counter(y_train)  # Count class occurrences
ratio = counter[0] / counter[1]
# Meta-Model (different from base models)
meta_model =  XGBClassifier(objective='binary:logistic',max_depth= 5,learning_rate=0.1,subsample=1,n_estimators=100,scale_pos_weight=ratio)

In [28]:
stacking_clf = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=5)

In [29]:
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('LRC',
                                LogisticRegression(class_weight='balanced',
                                                   random_state=0)),
                               ('DTC',
                                DecisionTreeClassifier(class_weight='balanced',
                                                       criterion='entropy',
                                                       random_state=0)),
                               ('RFC',
                                RandomForestClassifier(class_weight='balanced',
                                                       criterion='entropy',
                                                       n_estimators=10,
                                                       random_state=0))],
                   final_estimator=XGBClassifier(base_score=None, bo...
                                                 feature_types=None, gamma=None,
                                                 grow_policy=None,
                                                 importance_type=None,
                                                 interaction_constraints=None,
                                                 learning_rate=0.1,
                                                 max_bin=None,
                                                 max_cat_threshold=None,
                                                 max_cat_to_onehot=None,
                                                 max_delta_step=None,
                                                 max_depth=5, max_leaves=None,
                                                 min_child_weight=None,
                                                 missing=nan,
                                                 monotone_constraints=None,
                                                 multi_strategy=None,
                                                 n_estimators=100, n_jobs=None,
                                                 num_parallel_tree=None,
                                                 random_state=None, ...))

In [30]:
y_pred=stacking_clf.predict(X_test)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
report=classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [32]:
print(report)
print(cm)

              precision    recall  f1-score   support

           0       0.26      0.55      0.35       194
           1       0.93      0.78      0.85      1406

    accuracy                           0.75      1600
   macro avg       0.59      0.67      0.60      1600
weighted avg       0.85      0.75      0.79      1600

[[ 107   87]
 [ 307 1099]]
