In [37]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
dataset= pd.read_csv("Preprocessed_dataset.csv")
dataset1=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [38]:
indep_x= dataset1.drop('Conversion',axis=1)
dep_y=dataset1['Conversion']

In [39]:
indep_x

Age  Income      AdSpend  ClickThroughRate  ConversionRate  \
0      56  136912  6497.870068          0.043919        0.088031   
1      69   41760  3898.668606          0.155725        0.182725   
2      46   88456  1546.429596          0.277490        0.076423   
3      32   44085   539.525936          0.137611        0.088004   
4      60   83964  1678.043573          0.252851        0.109940   
...   ...     ...          ...               ...             ...   
7995   21   24849  8518.308575          0.243792        0.116773   
7996   43   44718  1424.613446          0.236740        0.190061   
7997   28  125471  4609.534635          0.056526        0.133826   
7998   19  107862  9476.106354          0.023961        0.138386   
7999   31   93002  7743.627070          0.185670        0.057228   

      WebsiteVisits  PagesPerVisit  TimeOnSite  SocialShares  EmailOpens  ...  \
0                 0       2.399017    7.396803            19           6  ...   
1                42       2.917138    5.352549             5           2  ...   
2                 2       8.223619   13.794901             0          11  ...   
3                47       4.540939   14.688363            89           2  ...   
4                 0       2.046847   13.993370             6           6  ...   
...             ...            ...         ...           ...         ...  ...   
7995             23       9.693602   14.227794            70          13  ...   
7996             49       9.499010    3.501106            52          13  ...   
7997             35       2.853241   14.618323            38          16  ...   
7998             49       1.002964    3.876623            86           1  ...   
7999             15       6.964739   12.763660             2          18  ...   

      PreviousPurchases  LoyaltyPoints  Gender_Male  CampaignChannel_PPC  \
0                     4            688            0                    0   
1                     2           3459            1                    0   
2                     8           2337            0                    1   
3                     0           2463            0                    1   
4                     8           4345            0                    1   
...                 ...            ...          ...                  ...   
7995                  7            286            1                    0   
7996                  5           1502            0                    0   
7997                  3            738            0                    0   
7998                  7           2709            0                    1   
7999                  9            341            0                    0   

      CampaignChannel_Referral  CampaignChannel_SEO  \
0                            0                    0   
1                            0                    0   
2                            0                    0   
3                            0                    0   
4                            0                    0   
...                        ...                  ...   
7995                         0                    0   
7996                         0                    1   
7997                         1                    0   
7998                         0                    0   
7999                         0                    0   

      CampaignChannel_Social Media  CampaignType_Consideration  \
0                                1                           0   
1                                0                           0   
2                                0                           0   
3                                0                           0   
4                                0                           0   
...                            ...                         ...   
7995                             0                           0   
7996                             0                           0   
7997                             0              

In [40]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
def selectkbest(indep_x,dep_y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_x,dep_y)
        featurename= fit1.get_support(indices=True)
        selected_features=dataset1.columns[featurename]
        features=selected_features.to_list()
        print(f"The {n} features are",features)
        selectk_features = fit1.transform(indep_x)
        return selectk_features

In [41]:
selectk_features=selectkbest(indep_x,dep_y,12)
selectk_features

The 12 features are ['Income', 'AdSpend', 'WebsiteVisits', 'PagesPerVisit', 'TimeOnSite', 'SocialShares', 'EmailOpens', 'EmailClicks', 'PreviousPurchases', 'LoyaltyPoints', 'CampaignChannel_Social Media', 'CampaignType_Consideration']


array([[1.36912000e+05, 6.49787007e+03, 0.00000000e+00, ...,
        6.88000000e+02, 0.00000000e+00, 0.00000000e+00],
       [4.17600000e+04, 3.89866861e+03, 4.20000000e+01, ...,
        3.45900000e+03, 0.00000000e+00, 0.00000000e+00],
       [8.84560000e+04, 1.54642960e+03, 2.00000000e+00, ...,
        2.33700000e+03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.25471000e+05, 4.60953464e+03, 3.50000000e+01, ...,
        7.38000000e+02, 1.00000000e+00, 0.00000000e+00],
       [1.07862000e+05, 9.47610635e+03, 4.90000000e+01, ...,
        2.70900000e+03, 1.00000000e+00, 0.00000000e+00],
       [9.30020000e+04, 7.74362707e+03, 1.50000000e+01, ...,
        3.41000000e+02, 0.00000000e+00, 0.00000000e+00]])

In [42]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size = 0.2, random_state = 42)   

In [43]:
X_train

Age  Income      AdSpend  ClickThroughRate  ConversionRate  \
1467   61   93885  5689.175098          0.279867        0.159560   
5768   36  132985  5424.122607          0.208562        0.101926   
5714   19  108713  3927.956305          0.171735        0.085737   
1578   56   58596  4292.600884          0.120824        0.061660   
6958   54   58585  1103.799992          0.116697        0.038537   
...   ...     ...          ...               ...             ...   
5226   56   78642  2940.130788          0.035823        0.169867   
5390   39  127845  6679.943050          0.152653        0.197298   
860    51  111150  4355.586567          0.184523        0.034020   
7603   57   55402  6740.116155          0.256332        0.133939   
7270   41  128061  1946.901695          0.293390        0.171930   

      WebsiteVisits  PagesPerVisit  TimeOnSite  SocialShares  EmailOpens  ...  \
1467             12       5.928037    0.649357            43          10  ...   
5768             36       8.176488   14.470432            89           4  ...   
5714              0       4.482721   11.193668            80          16  ...   
1578             16       9.437501    7.128225            27           3  ...   
6958             31       3.663657    0.631376            99           7  ...   
...             ...            ...         ...           ...         ...  ...   
5226             25       1.464216   12.634534            21           1  ...   
5390             30       4.940007   13.160262             7           6  ...   
860              15       2.937878    8.336308            44          10  ...   
7603             10       8.001640   10.509658            71           7  ...   
7270              1       4.097645   14.232220            26          12  ...   

      PreviousPurchases  LoyaltyPoints  Gender_Male  CampaignChannel_PPC  \
1467                  0           3990            1                    0   
5768                  5           3761            1                    1   
5714                  9           3612            0                    0   
1578                  8            336            1                    0   
6958                  7           2514            0                    1   
...                 ...            ...          ...                  ...   
5226                  8           3044            0                    1   
5390                  6           4010            0                    0   
860                   5            398            1                    1   
7603                  8           3375            1                    0   
7270                  4           2759            1                    0   

      CampaignChannel_Referral  CampaignChannel_SEO  \
1467                         0                    0   
5768                         0                    0   
5714                         0                    1   
1578                         0                    0   
6958                         0                    0   
...                        ...                  ...   
5226                         0                    0   
5390                         0                    0   
860                          0                    0   
7603                         1                    0   
7270                         0                    1   

      CampaignChannel_Social Media  CampaignType_Consideration  \
1467                             1                           0   
5768                             0                           0   
5714                             0                           0   
1578                             1                           0   
6958                             0                           0   
...                            ...                         ...   
5226                             0                           0   
5390                             0                           0   
860                              0              

In [23]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='auto', random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [44]:
#from imblearn.over_sampling import RandomOverSampler
#ros = RandomOverSampler(random_state=42)
#X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
from sklearn.ensemble import StackingClassifier

In [49]:
base_models=[('LRC',LogisticRegression(random_state = 0)),('DTC',DecisionTreeClassifier(criterion = 'entropy', random_state = 0)),('RFC', RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0))]

In [50]:
from xgboost import XGBClassifier
from collections import Counter
counter = Counter(y_train)  # Count class occurrences
ratio = counter[0] / counter[1]
# Meta-Model (different from base models)
meta_model =  XGBClassifier(objective='binary:logistic',max_depth= 5,learning_rate=0.1,subsample=1,n_estimators=100)

In [51]:
stacking_clf = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=5)

In [52]:
stacking_clf.fit(X_train_resampled,y_train_resampled )

StackingClassifier(cv=5,
                   estimators=[('LRC', LogisticRegression(random_state=0)),
                               ('DTC',
                                DecisionTreeClassifier(criterion='entropy',
                                                       random_state=0)),
                               ('RFC',
                                RandomForestClassifier(criterion='entropy',
                                                       n_estimators=10,
                                                       random_state=0))],
                   final_estimator=XGBClassifier(base_score=None, booster=None,
                                                 callbacks=None,
                                                 colsample_bylevel=None,
                                                 colsample_bynode=None,
                                                 c...
                                                 feature_types=None, gamma=None,
                                                 grow_policy=None,
                                                 importance_type=None,
                                                 interaction_constraints=None,
                                                 learning_rate=0.1,
                                                 max_bin=None,
                                                 max_cat_threshold=None,
                                                 max_cat_to_onehot=None,
                                                 max_delta_step=None,
                                                 max_depth=5, max_leaves=None,
                                                 min_child_weight=None,
                                                 missing=nan,
                                                 monotone_constraints=None,
                                                 multi_strategy=None,
                                                 n_estimators=100, n_jobs=None,
                                                 num_parallel_tree=None,
                                                 random_state=None, ...))

In [53]:
y_pred=stacking_clf.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [54]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
report=classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [55]:
#Ros
print(report)
print(cm)

              precision    recall  f1-score   support

           0       0.68      0.07      0.12       194
           1       0.89      1.00      0.94      1406

    accuracy                           0.88      1600
   macro avg       0.78      0.53      0.53      1600
weighted avg       0.86      0.88      0.84      1600

[[  13  181]
 [   6 1400]]


In [36]:
#SMOTE
print(report)
print(cm)

              precision    recall  f1-score   support

           0       0.30      0.25      0.28       194
           1       0.90      0.92      0.91      1406

    accuracy                           0.84      1600
   macro avg       0.60      0.59      0.59      1600
weighted avg       0.83      0.84      0.83      1600

[[  49  145]
 [ 113 1293]]
